FROM --platform=linux/amd64 public.ecr.aws/lambda/python:3.9

# Copy requirements first to leverage Docker cache
COPY requirements.txt ${LAMBDA_TASK_ROOT}/
RUN pip install -r requirements.txt --target ${LAMBDA_TASK_ROOT}

# Copy function code
COPY handler.py ${LAMBDA_TASK_ROOT}/

# Set the working directory
WORKDIR ${LAMBDA_TASK_ROOT}