service: ai-rpg-game

provider:
  name: aws
  runtime: python3.9
  region: eu-central-1
  environment:
    TOGETHER_API_KEY: ${ssm:/ai-rpg/together-api-key}
  iam:
    role:
      statements:
        - Effect: Allow
          Action: ssm:GetParameter
          Resource: 
            - arn:aws:ssm:${aws:region}:${aws:accountId}:parameter/ai-rpg/together-api-key

package:
  individually: true
  exclude:
    - node_modules/**
    - frontend/**
    - dist/**
    - __pycache__/**
    - .git/**
    - ".DS_Store"
    - "*.log"

functions:
  api:
    handler: handler.handler
    package:
      artifact: ./ai-rpg-game.zip
    layers:
      - arn:aws:lambda:eu-central-1:507651926113:layer:ai-rpg-dependencies:6
    events:
      - http:
          path: /test
          method: get
          cors:
            origin: 'https://www.craigdoesdata.com'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true
      - http:
          path: /api/game/action
          method: post
          cors:
            origin: 'https://www.craigdoesdata.com'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true
      - http:
          path: /api/game/action
          method: options
          cors:
            origin: 'https://www.craigdoesdata.com'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true
plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    slim: true
    strip: false
    noDeploy:
      - numpy
      - pyarrow
      - pillow